command /test [<text>]:
    trigger:

        #if arg 1 is "help":
        #    send "Help"
        #else if all players contain arg 1:
        #    send arg 1

        #arg 1 is "help"
        #send "Help"
        #arg 1 is "Test"
        #send "test"

        load yaml "plugins/Skript/yaml/test.yml" as "test"
        set yaml value "test.test2" from "test" to "hello world"
        #delete {test::*}
        set {_test::*} to true
        set {_test::3} to true
        set {_test::10} to true
        set yaml list "list.test" from "test" to {_test::*}
        #test()
        save yaml "test"
        #delete {test::5}
        #loop {test::*}:
        #    send "&7%loop-index% &f%loop-value%"
        #console command "tellraw @a ""§1TEST """
        #send "&c⚠ &7Warning"
        #send "&9ⓘ &7Info"
        #send "&e⚡ &7  Debug"
        set {_test} to yaml value "words" from "test"
        broadcast size of yaml list "words" from "test"
        broadcast {_test}
        loop yaml node keys "words" from "test":
            broadcast yaml value "words.%loop-val%" from "test"
            #broadcast "%loop-id% - %loop-val% - %loop-list% - %loop-node% - %loop-key% - %loop-subnodekeys%"
            #broadcast yaml value loop-node from loop-id
        

# function testAdd(t: text, n: text):
#     set yaml value "swear.%{_n}%" from "test" to {_t}

# function test():
#     testAdd(".*[fF]+[\d|\W|_]*[uUoOvVaA0-9@*]*[\d|\W|_]*[cCwW]+[\d|\W|_]*[kK]+.*", "Fuck")
#     testAdd(".*[bB][\d|\W|_]*[iI!lL1-9]*[\d|\W|_]*[tT]+[\d|\W|_]*[cC]+[\d|\W|_]*[hH]+.*", "Bitch")
#     testAdd(".*[bB][\d|\W|_]*[aA@0-9]*[\d|\W|_]*[sS]+[\d|\W|_]*[tT]+[\d|\W|_]*[aA@0-9]*[rR]+[\d|\W|_]*[dD]+.*", "Bastard")
#     testAdd(".*\b[aA@1-9]+[\d|\W|_]*([sS$][\d|\W|_]*){2}([hH]+[\d|\W|_]*[oO0]+[\d|\W|_]*[lL]+[\d|\W|_]*[eE3].*)*(\b|$).*", "Ass")
#     testAdd(".*\b[nN]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*([gG]+[\d|\W|_]*){2}[eEaA1@0-9]*[\d|\W|_]*[rR]*.*", "Nigger")
#     testAdd(".*\b[rR]+[\d|\W|_]*[aA@]+[\d|\W|_]*[pP]+[\d|\W|_]*[eE]+\b.*", "Rape")
#     testAdd(".*[sS$]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[uUvV@*]+[\d|\W|_]*[tT]+.*", "Slut")
#     testAdd(".*[wW]+[\d|\W|_]*[hH]+[\d|\W|_]*[oO0]+[\d|\W|_]*[rR]+[\d|\W|_]*[eE3]+\b.*", "Whore")
#     testAdd(".*\b[hH]+[\d|\W|_]*[oO]+[\d|\W|_]*[eE][\d|\W|_]*[sS]*\b.*", "Hoe")
#     testAdd(".*\b[fF]+[\d|\W|_]*[@aA1-9]+[\d|\W|_]*[gG]+[\d|\W|_]*[sSoO]*.*", "Fag")
#     testAdd(".*\b[rR]+[\d|\W|_]*[eE3]+[\d|\W|_]*[tT]+[\d|\W|_]*[aA@0-9]+[\d|\W|_]*[rR]+[\d|\W|_]*[dD]+.*", "Retard")
#     testAdd(".*\b[sS]+[\d|\W|_]*[hH]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[tT]+.*", "Shit")
#     testAdd(".*\b[kK]+[yY]+[sS]+\b.*", "KYS")
#     testAdd(".*\b[sS]+[\d|\W|_]*[hH]+[\d|\W|_]*[oO0]+[\d|\W|_]*[oO0]+[\d|\W|_]*[tT]+[\d|\W|_]*[iI!lL1-9]+.*","Shooting")
#     testAdd(".*\b[hH]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[tT]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[eE3aA@0-9]+[\d|\W|_]*[rR]+.*", "Hitler")
#     testAdd(".*\b[nN]+[\d|\W|_]*[aA@0-9]+[\d|\W|_]*[zZ]+[\d|\W|_]*[iI]+.*", "Nazi")
#     #Body / Anatomy
#     testAdd(".*[vV]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[rR]+[\d|\W|_]*[gG]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[nN]+\b.*", "virgin")
#     testAdd(".*\b[pP]+[\d|\W|_]*[eE3]+[\d|\W|_]*[nN]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[sS]+.*", "Penis")
#     testAdd(".*\b[dD]+[\d|\W|_]*[iI!1-9]+[\d|\W|_]*[cC]*[\d|\W|_]*[kK]+.*", "Dick")
#     testAdd(".*\b[dD]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[iI!lL1-9]+[\d|\W|_]*[dD]+[\d|\W|_]*[oO0]+.*", "Dildo")
#     testAdd(".*\b[cC]+[\d|\W|_]*[oO0]+[\d|\W|_]*[cC]+[\d|\W|_]*[kK]+([\d|\W|_]*[yYiI1]+)*\b.*", "Cock")
#     testAdd(".*\b[cC]+[\d|\W|_]*[uUoOvV@\*]+[\d|\W|_]*[mM]+\b.*", "Cum")